### ISSUE TITLE
demo.py issue

### ISSUE THREAD

**Issue by WangWeijie1998** [weitong8591/ars_magsac#1]
Hello friend, there is an error in the following picture when I run the demo.py , could you help me?
![屏幕截图 2023-11-29 165354](https://github.com/weitong8591/ars_magsac/assets/99522912/e6260573-9870-4413-bc84-654604e1efcc)

**Comment by WangWeijie1998** [comment]
![屏幕截图 2023-11-29 165354](https://github.com/weitong8591/ars_magsac/assets/99522912/e9073b7f-928b-4834-ac1b-1117d385d668)

**Comment by WangWeijie1998** [comment]
![image](https://github.com/weitong8591/ars_magsac/assets/99522912/9cfa3dab-7bfd-466c-ba3e-e70e555733ee)
pts1 is different from other shapes.

**Comment by weitong8591** [comment]
Hi, it might becaseu you use OpenCV=4.x, while I was using 3.x on this work. I will commit updates making sure it is compliable on both CV versions.

**Comment by WangWeijie1998** [comment]
That would be great, thank you, friend. I will try using OpenCV=3. x.

**Comment by WangWeijie1998** [comment]
That would be great, thank you, friend.
