### ISSUE TITLE
demo issue

### ISSUE THREAD

**Issue by WangWeijie1998** [weitong8591/ars_magsac#2]
![屏幕截图 2023-11-29 201623](https://github.com/weitong8591/ars_magsac/assets/99522912/fd1777b1-71a5-4cda-8639-d7f80ba5e50d)
Hello friend, I'm sorry to bother you again. I used the "pip install pymagsac" command to install pymagsac, but ran the demo.py command in readme and the result was incorrect. I hope to receive your help again.（Teacher Danini's project was not successfully installed, so I used "pip install pymagsac" to install it）

**Comment by weitong8591** [comment]
Hi! It doesn't matter which way you choose to install MAGSAC. Now it's easy to install it through pip, but please pay attention to different arguments from what I used, e.g, correspondences = [x1, y1, x2, y2] in (n, 4).

**Comment by WangWeijie1998** [comment]
Sorry for the delay in responding. Thank you for your help. Wishing you a Merry Christmas in advance!

**Comment by ABCDZLG** [comment]
> ![屏幕截图 2023-11-29 201623](https://private-user-images.githubusercontent.com/99522912/286591563-fd1777b1-71a5-4cda-8639-d7f80ba5e50d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NjIzMjUsIm5iZiI6MTcyMjg2MjAyNSwicGF0aCI6Ii85OTUyMjkxMi8yODY1OTE1NjMtZmQxNzc3YjEtNzFhNS00Y2RhLTg2MzktZDdmODBiYTVlNTBkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDEyNDcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNDMwMmJiMmEyYzdlZDg1OGJiNTZkYTg2ODU2MWFmMDQ5OWQ5ZjNkMTdmOTI0MGI2YjgxZDEyOGIwZGMxYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GBU0zAbkAxdHJocKNU8KImpmD5UKnQ0lXL6XW-2o7UI) Hello friend, I'm sorry to bother you again. I used the "pip install pymagsac" command to install pymagsac, but ran the demo.py command in readme and the result was incorrect. I hope to receive your help again.（Teacher Danini's project was not successfully installed, so I used "pip install pymagsac" to install it）

您好，我和您产生了一样的错误，我想请问一下您这个是怎样解决的？谢谢
